[package]
name = "libooz-sys"
version = "0.1.0"
authors = ["David Herberth <github@dav1d.de>"]
edition = "2021"
license = "GPL-3.0-or-later"
build = "build.rs"

[dependencies]

[build-dependencies]
cc = "1.0"
